let elements = {
    "gold": document.getElementById("gold"),
    "income": document.getElementById("income"),
    "heroes": document.getElementById("heroes"),
    "travelers": document.getElementById("travelers"),
    "time": document.getElementById("time"),
    "charactersUi": document.getElementById("charactersUi"),
    "debug1": document.getElementById("debug1"),
    "debug2": document.getElementById("debug2"),
    "debug3": document.getElementById("debug3"),
    "debug4": document.getElementById("debug4"),
    "debug5": document.getElementById("debug5"),
    "window0": document.getElementById("window0"),
    "windowHeader0": document.getElementById("windowHeader0"),
    "windowBody0": document.getElementById("windowBody0"),
    "window1": document.getElementById("window1"),
    "windowHeader1": document.getElementById("windowHeader1"),
    "windowBody1": document.getElementById("windowBody1"),
    "window2": document.getElementById("window2"),
    "windowHeader2": document.getElementById("windowHeader2"),
    "windowBody2": document.getElementById("windowBody2"),
}
